#tutorial for the beginning.
def gent():
    print("================GENERAL TUTORIAL===================")
    print("A.\tCharacters")
    print("In Warrior's Quest, you have 4 major classes to choose from: Fighter, Barbarian, Mage and Healer.\nEach have their own unique strengths and weaknesses. You can find their descriptions below:")
    print("1.\tFighter\n")
    print("A soldier-like warrior, with great balance of offence and defence, and good weapon proficiency in all weapons. Has great agility, but is completely lacking in magical potential and strength.\n Has the special ablity FOCUS, which improves chances of hitting target by 100%.")
    print("2.\tBarbarian\n")
    print("A merciless warrior, who focuses mainly on attack and damage, but cares very little for defence and agility. Can use magic to improve damage potential and power.")
    print("Has the special ability RAGE, which improves his damage by 50%.")
    print("3.\tMage\n")
    print("A relentless user of magic, who operates from a longer range and is capable of moving around easily and defending, but is incapable of close-quarters combat and melee fighting.\nHas special ability POTENCY, which improves damage of magical attacks by 100%.")
    print("4.\tHealer\n")
    print("A synergy nased class, they provide great healing and can revive killed teammates. They have great defence and agility, but are incapable of any form of attack, and cannot survive for long in a close-quarters combat situation. Have extended inventory.\nHas special ability WIND, which drastically improves healing.")
    print("\nB.\tGameplay")
    print("This game gives you the option to proceed through the game by choosing your actions, including progressing through the game, accessing your inventory, making purchases at shops, choosing attacks in combat. This section only details on non-combat situations.")
    print("You will be given options on what to do during sections of the game. Some options will depend on where you are in the game (marketplaces, inns, or challenge areas). You may have the following options:")
    print("1. Show Status - This shows the active character's current situation - HP, MP, Weapons, Spells, and activation of special ability.")
    print("2. Access Inventory - Check your inventory, and what items are in it.")
    print("3. Use Item - Use an item in your inventory.")
    print("4. Discard item - Remove an item from your inventory without using it.")
    print("5. Buy/Sell - Avilable only at shops and marketplaces")
    print("6. Upgrade - Available only at blacksmiths and magic-sellers.")
    print("7. Accept/Decline Challenge - Only available in challenge areas.")
    print("\nC.\tCombat")
    print("The combat system of this game is simple to understand and master. Combat is divided into turns between you and your opponent(s), and the one who goes first is the one who made the challenge or the one who initiated the encounter.")
    print("For each of your turns, you have the following options:")
    print("1. Attack - Melee\n2. Cast - Magic\n3. Spare - not act\n4. Special Ability - Activate")
    print("For your opponent's turn, you may:")
    print("1. Dodge - Some distance away.\n2. Block - may take some damage\n3. Parry - Attempt to deflect attack (luck based)")
    print("\nD. Items")
    print("Items in this game can have various effects, from healing, to stat boosts, to damage upgrades, and so on. You may get items from shops, as rewards for an encounter, or as rewards for completing challenges.")
    print("That concludes the general tutorial for this game. This is all the information you NEED to know before starting a game or playing. The rest is best learnt through gameplay. Good luck!")
    return

